### ISSUE TITLE
New push

### ISSUE THREAD

**Issue by DanKE-Leipzig** [clld/apics-texts#222]
Hallo Robert,

ich habe die Texte für die folgenden Kapiteln geändert. Könntest Du die neuen Texte neu ins Internet stellen, bitte?

Chapter 2
Chapter 30
Chapter 31
Chapter 32
Chapter 33
Chapter 34
Chapter 36
Chapter 40
Chapter 42
Chapter 43
Chapter 47
Chapter 50

Vielen Dank im Voraus.

Mit freundlichen Grüßen,
Dan

**Comment by xrotwang** [comment]
Ich seh noch keinen [pull request](https://github.com/clld/apics-texts/pulls). Machst Du den noch, um Deine Änderungen in dieses repository zu bekommen?

**Comment by DanKE-Leipzig** [comment]
Ja, das Problem ist, als ich die Texte geändert habe, habe ich nicht auf den "Push"-Button gedruckt, sondern nur den "Speichern"-Button. Jetzt wenn es keine Änderung gegeben ist, kann ich es nicht neu speichern oder pushen. Ich habe daher in den Texte immer "<link href="http://apics-online.info/clld-static/css/packed.22d6c95d.css" rel="stylesheet">" hinzugefügt und somit "pull request" geschickt. Ich hoffe, dass es in Ordnung ist. Danke!

**Comment by xrotwang** [comment]
Hallo @DanKE-Leipzig!
Ich weiss nicht genau, was die Idee bei diesen Änderungen ist. Die Zeile, die Du einfügst, wird beim display in der web app eh eingefügt. Diese Arbeit kannst Du Dir also sparen - bzw. kann man sowas natürlich auch schnell automatisiert machen.

**Comment by DanKE-Leipzig** [comment]
Ja, die Änderung habe ich früher schon hinzugefügt, diesmal habe ich nur diese Zeile hinzugefügt, damit ich die Texten pushen kann.

**Comment by xrotwang** [comment]
Aber diese eine Zeile ist die einzige Änderung zum bisherigen Zustand in diesem repository. D.h. Deine übrigen Änderungen sind eh schon drin?

**Comment by DanKE-Leipzig** [comment]
Ja, die Änderungen habe ich in den letzten zwei Wochen gemacht. Aber ich habe damals nicht auf "push" gedruckt.

**Comment by DanKE-Leipzig** [comment]
Ich kenne die Funktionen noch nicht so gut aus. Sorry...

**Comment by xrotwang** [comment]
Habe die pull requests geschlossen, weil sie keine wesentlichen Änderungen enthielten, die nicht schon im repository sind.

**Comment by DanKE-Leipzig** [comment]
Es ist nämlich so, ich habe in den letzten zwei Wochen Änderungen da eingebaut, wenn man auf "History" klickt, sieht man die Änderungen. Daher sind die Texte anderes als was jetzt aufs Internet sind. Wir möchten gerne, dass diese neue Version von den Texten auf Internet kommt, damit wir darauf Korrektur lesen können.

**Comment by DanKE-Leipzig** [comment]
Also: die Veränderungen von heute sind nicht wesentlich, sondern die, die von den letzten Wochen gemacht worden sind, aber nicht gepusht worden sind. @nicobenz

**Comment by xrotwang** [comment]
Hm. Wie soll ich aber an diese Änderungen kommen? Der momentane Zustand in diesem repository (clld/apics-texts) ist auch online unter http://apics-online.info
Andere Änderungen kann es also wohl nur in Euren privaten forks von clld/apics-texts geben. Um an die zu kommen, müßt ihr Pull Requests machen. (Das wäre zumindest der workflow, wenn Ihr etwa mit github desktop oder ähnlichem arbeitet.)

**Comment by DanKE-Leipzig** [comment]
Okay. Alles klar. Dann schauen wir vielleicht am besten erstmal die jetzigen Texte an und wenn nächste Mal was zu ändern gibt, machen wir Pull Requests. Ich habe früher auch nie mit Github gearbeitet und lerne jetzt immer was neues darüber. Dankeschön!
