### ISSUE TITLE
Tabelle nach links gerutscht 

### ISSUE THREAD

**Issue by DanKE-Leipzig** [clld/apics-texts#236]
16 Ghanaian Pidgin English: alle Tabelle in diesem Kapitel sind nach links gerutscht.

**Comment by xrotwang** [comment]
Wo sollen die Tabellen denn sonst sein? Nicht left-aligned?

**Comment by DanKE-Leipzig** [comment]
![16](https://user-images.githubusercontent.com/26629916/27955899-4bf47dac-6317-11e7-94df-0505128a6490.jpeg)

Jetzt sehen alle Tabelle nämlich so aus.

**Comment by xrotwang** [comment]
Bei mir nicht:

![apics](https://user-images.githubusercontent.com/870184/27956949-59f8d164-631c-11e7-8985-c33352d02b41.png)

**Comment by xrotwang** [comment]
Vielleicht hilft "shift-reload" im browser?

**Comment by DanKE-Leipzig** [comment]
Dankeschön für die Hinweise! Ich habe Susanne auch gefragt, in ihrem Computer sieht es auch normal aus. Ich schließe daher jetzt diese Issue. Vielen Dank!
